name: Dependency Audit

on:
  push:
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
  schedule:
    - cron: '42 7 * * 6'  # Every Saturday at 07:42 UTC
  workflow_dispatch:

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions-rs/audit-check@35b7b53b1e25b55642157ac01b4adceb5b9ebef3 # v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
