name: Security Audit

on:
  push:
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
  schedule:
    - cron: '42 7 * * 6'  # Every Saturday at 07:42 UTC
  workflow_dispatch:

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
