name: Release

on:
  push:
    tags: [ v*.*.* ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.job.os }}
    strategy:
      matrix:
        job:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            use-cross: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.56.1 # minimum supported rust version
          target: ${{ matrix.job.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.job.use-cross }}
          command: test
          args: --target ${{ matrix.job.target }} ${{ matrix.job.flags }}

  deploy:
    name: Push
    needs: [ test ]
    runs-on: ${{ matrix.job.os }}
    strategy:
      matrix:
        job:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            rustflags: -C target-feature=+crt-static
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            use-cross: true
    steps:
      - uses: actions/checkout@v4

      - name: Set RUSTFLAGS env variable
        if: matrix.job.rustflags
        shell: bash
        run: echo "RUSTFLAGS=${{ matrix.job.rustflags }}" >> $GITHUB_ENV

      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.job.use-cross }}
          command: build
          args: --release --target ${{ matrix.job.target }} ${{ matrix.job.flags }}

      - name: Strip release binary
        if: matrix.job.os != 'windows-latest'
        run: |
          strip "target/${{ matrix.job.target }}/release/furnel"

      - id: get_version
        uses: battila7/get-version-action@v2

      - name: Package
        shell: bash
        run: |
          if [ "${{ matrix.job.os }}" = "windows-latest" ]; then
            bin="target/${{ matrix.job.target }}/release/furnel.exe"
          else
            bin="target/${{ matrix.job.target }}/release/furnel"
          fi
          staging="furnel-${{ steps.get_version.outputs.version }}-${{ matrix.job.target }}"

          cp CHANGELOG.md LICENSE.md README.md $bin $staging

          if [ "${{ matrix.job.os }}" = "windows-latest" ]; then
            7z a "$staging.zip" $staging
          elif [ "${{ matrix.job.os }}" = "macos-latest" ]; then
            gtar czvf "$staging.tar.gz" $staging
          else
            tar czvf "$staging.tar.gz" $staging
          fi

      - name: Package (debian)
        if: matrix.job.target == 'x86_64-unknown-linux-musl'
        shell: bash
        run: |
          cargo install cargo-deb
          cargo deb --no-build --target ${{ matrix.job.target }}
          cp "target/${{ matrix.job.target }}/debian"/*.deb ./

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
            files: 'furnel*'
            draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
